Edit xnu patches to reflect renamed variable

diff --git a/patches/xnu-4903.221.2.availability_versions.p1.patch b/patches/xnu-4903.221.2.availability_versions.p1.patch
--- a/patches/xnu-4903.221.2.availability_versions.p1.patch
+++ b/patches/xnu-4903.221.2.availability_versions.p1.patch
@@ -8,8 +8,8 @@ index ef47e37..a1e694a 100755
 
 -if [ ! -x "${SDKROOT}/usr/local/libexec/availability.pl" ] ; then
 -    echo "Unable to locate ${SDKROOT}/usr/local/libexec/availability.pl (or not executable)" >&2
-+if [ ! -x "${DEPENDENCIES_DIR}/usr/local/libexec/availability.pl" ] ; then
-+    echo "Unable to locate ${DEPENDENCIES_DIR}/usr/local/libexec/availability.pl (or not executable)" >&2
++if [ ! -x "${DEPROOT}/usr/local/libexec/availability.pl" ] ; then
++    echo "Unable to locate ${DEPROOT}/usr/local/libexec/availability.pl (or not executable)" >&2
      exit 1
  fi
 
@@ -18,7 +18,7 @@ index ef47e37..a1e694a 100755
  EOF
 
 -for ver in $(${SDKROOT}/usr/local/libexec/availability.pl --ios) ; do
-+for ver in $(${DEPENDENCIES_DIR}/usr/local/libexec/availability.pl --ios) ; do
++for ver in $(${DEPROOT}/usr/local/libexec/availability.pl --ios) ; do
      ver_major=${ver%.*}
      ver_minor=${ver#*.}
      value=$(printf "%d%02d00" ${ver_major} ${ver_minor})
@@ -27,7 +27,7 @@ index ef47e37..a1e694a 100755
  done
 
 -for ver in $(${SDKROOT}/usr/local/libexec/availability.pl --macosx) ; do
-+for ver in $(${DEPENDENCIES_DIR}/usr/local/libexec/availability.pl --macosx) ; do
++for ver in $(${DEPROOT}/usr/local/libexec/availability.pl --macosx) ; do
      set -- $(echo "$ver" | tr '.' ' ')
      ver_major=$1
      ver_minor=$2
